/*
 * Name: Hacker Bot - Docker Bot.
 * Author: Arafat Hossain Ar
 * Date: 1/05/2020
 * All right reserved. Don't copy single line of code without permission.
 */
package hackerbot;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Arafat Hossain Ar
 */
public class Bot extends javax.swing.JFrame {

    /**
     * Creates new form Bot
     */
    // Variable declararion
    //Time and date
    Timer timer;
    int DELAY = 100;
    //Mouse Position
    int xMouse;
    int yMouse;

    public Bot() {
        initComponents();
        String greet = "                                   <Command Execution>\n";
        outputbox.setText(greet);

        //time update
        timer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date currentTime = new Date();
                String formatTimer = "hh:mm:ss";
                DateFormat formattime = new SimpleDateFormat(formatTimer);
                String formattedtimer = formattime.format(currentTime);
                displayclock.setText(formattedtimer);
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                Date date = new Date();
                displaydate.setText(formatter.format(date));

            }

        });
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        titlebarpanel = new javax.swing.JPanel();
        exitbtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        infopanel = new javax.swing.JPanel();
        displayclock = new javax.swing.JLabel();
        displaydate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        disk = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputbox = new javax.swing.JTextArea();
        inputbox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hacker Bot");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlebarpanel.setBackground(new java.awt.Color(0, 0, 0));
        titlebarpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarpanelMouseDragged(evt);
            }
        });
        titlebarpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarpanelMousePressed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/exit.png"))); // NOI18N
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/title.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel18.setText("Docker Bot");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/help.png"))); // NOI18N

        javax.swing.GroupLayout titlebarpanelLayout = new javax.swing.GroupLayout(titlebarpanel);
        titlebarpanel.setLayout(titlebarpanelLayout);
        titlebarpanelLayout.setHorizontalGroup(
            titlebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarpanelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn)
                .addContainerGap())
        );
        titlebarpanelLayout.setVerticalGroup(
            titlebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(titlebarpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        infopanel.setBackground(new java.awt.Color(51, 51, 51));
        infopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayclock.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        displayclock.setForeground(new java.awt.Color(102, 255, 102));
        displayclock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayclock.setText("12:34:78");
        infopanel.add(displayclock, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 194, 29));

        displaydate.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        displaydate.setForeground(new java.awt.Color(102, 255, 102));
        displaydate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displaydate.setText("12:34:78");
        infopanel.add(displaydate, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 58, 194, 29));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("CPU:46%");
        infopanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));

        disk.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        disk.setForeground(new java.awt.Color(102, 255, 102));
        disk.setText("DISK:80%");
        infopanel.add(disk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("RAM:75%");
        infopanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/titlename.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 50));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name: Docker Bot");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Version: 1.0");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Author: Arafat Hossain Ar");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 20));

        infopanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 0, 270, 110));

        jPanel1.add(infopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 110));

        outputbox.setEditable(false);
        outputbox.setBackground(new java.awt.Color(0, 0, 0));
        outputbox.setColumns(20);
        outputbox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outputbox.setForeground(new java.awt.Color(51, 255, 51));
        outputbox.setLineWrap(true);
        outputbox.setRows(5);
        outputbox.setWrapStyleWord(true);
        outputbox.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250)), null));
        outputbox.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        outputbox.setFocusable(false);
        jScrollPane1.setViewportView(outputbox);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 460, 460));

        inputbox.setBackground(new java.awt.Color(0, 0, 0));
        inputbox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inputbox.setForeground(new java.awt.Color(102, 255, 102));
        inputbox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputbox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 1, true));
        inputbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputboxActionPerformed(evt);
            }
        });
        jPanel1.add(inputbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 240, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/file.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/setting.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/linix.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/wifi.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/pass.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/search.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/tor.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hackerbot/image/chrome.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10))
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 240, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titlebarpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarpanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();


    }//GEN-LAST:event_titlebarpanelMousePressed

    private void titlebarpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarpanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_titlebarpanelMouseDragged

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void inputboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputboxActionPerformed
        // TODO add your handling code here:
        String gtext = inputbox.getText().toLowerCase();
        outputbox.append("->: " + gtext + "\n");
        inputbox.setText("");
        //Greetings panel
        if (gtext.contains("hi")) {
            jbot("Hi Boss!");
        } else if (gtext.contains("how")) {
            jbot("Fine sir. And you?");
        } else if (gtext.contains("fine")) {
            jbot("Good to hear that");
        } //time date panel
        else if (gtext.contains("date")) {
            // jbot("Date is: " + date);
        } else if (gtext.contains("time")) {
            //jbot("Time is: " + formattedtimer);
        } //version panel
        else if (gtext.contains("name")) {
            jbot("My Name is Docker Bot");
        } else if (gtext.contains("version")) {
            jbot("My version is: KB 1.0 Silver");
        } else if (gtext.contains("about")) {

            jbot("My name is Kilobyte" + "\n Version: KB 1.0 Silver" + "\n I'm a SuperBot Created by: Arafat Hossain Ar");
        } else if (gtext.contains("creator")) {
            jbot("My creator name is: Arafat Hossain Ar");

        } //Java panel
        else if (gtext.contains("java")) {
            jbot("Java is a object oriented programming language and computing platform first released by Sun Microsystems in 1995. ");
        } //utility panel
        else if (gtext.contains("notepad")) {
            jbot("Opening notepad");
            Robot robot = null;
            try {
                robot = new Robot();
            } catch (AWTException ex) {
            }
            robot.delay(1000);
            Runtime run = Runtime.getRuntime();
            try {
                run.exec("notepad.exe");
            } catch (IOException ex) {
            }

        } //other information
        else if (gtext.contains("facebook")) {
            jbot(" Facebook is a website for the Worldwide Social Interaction System, which was established on February 7, 2015. It can be a free member. It is owned by Facebook Inc.");

        } else if (gtext.contains("google")) {
            jbot("Google Search is the largest search engine on the web. Google's goal is to \"make all the information in the world organized and make it publicly available.\" This is the largest search engine. Google receives about 10 million search requests daily through its various services.");
        } else if (gtext.contains("internet")) {
            jbot("The Internet is not synonymous with World Wide Web. The Internet is a massive network of networks, a networking infrastructure. It connects millions of computers together globally, forming a network in which any computer can communicate with any other computer as long as they are both connected to the Internet");
        } //last greetings
        else if (gtext.contains("thanks")) {
            jbot("Welcome bro");
        } else if (gtext.contains("night")) {
            jbot("Good Night too bro. Have Sweet a Dream");
        } else if (gtext.contains("allah")) {
            jbot("Allah Hafez");
        } else if (gtext.contains("ping: 127.0.0.1")) {
        } //defualt command panel
        else {
            final int num = 3;
            double r = Math.random();
            int rand = (int) (r * num);
            String bot = "";
            if (rand == 0) {
                jbot("I Don't Understand");
            } else if (rand == 1) {
                jbot("Sorry, I Don't Understand");
            } else if (rand == 2) {
                jbot("I'm Not Programmed to Response that");
            } else if (rand == 3) {
                jbot("Come Again Please");
            }
        }

    }//GEN-LAST:event_inputboxActionPerformed
    private void jbot(String string) {
        outputbox.append("->: " + string + "\n");

    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, AWTException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bot().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disk;
    private javax.swing.JLabel displayclock;
    private javax.swing.JLabel displaydate;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JPanel infopanel;
    private javax.swing.JTextField inputbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputbox;
    private javax.swing.JPanel titlebarpanel;
    // End of variables declaration//GEN-END:variables
}
